# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170719_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='message_images/'),
        ),
    ]
